version: "3"

services:
  mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 20211107
    restart: always

  redis:
    image: redis
    volumes:
      - /data/redis/redis.conf:/etc/redis/redis.conf
      - /data/redis/data:/data
    ports:
      - "6379:6379"
    privileged: true
    restart: always

  ss-assistant:
    image: hgamiui9/ss-assistant:1.3.39
    ports:
      - "1107:1107"
    env_file:
      - /root/github/ss-assistant/.env
    restart: always
    labels:
      logging: promtail

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /nginx/ssl/syntsugar.chat_bundle.crt:/etc/ssl/certs/syntsugar_certificate.crt
      - /nginx/ssl/syntsugar.chat.key:/etc/ssl/private/syntsugar_private.key
    depends_on:
      - ss-assistant
    restart: always
