version: "3"

services:
  mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 20241001
    restart: always

  ws:
    image: hgamiui9/ss-wecom-assistant:2.2.8
    ports:
      - "1107:1107"
    env_file:
      - /root/github/ss-wecom-assistant/.env
    restart: always
